### DISCUSSION TITLE
About icons and folder: acode.icons and acode.folders

### DISCUSSION THREAD

**Discussion by sebastianjnuwu** [Acode-Foundation/Acode#779] [Ideas]
Hello, I have an icon plugin in acode, but the way I add the icons is very annoying, in addition to the code being very ugly, I wanted to help other developers to do this:

```js
const icons = acode.icons({
  astro: { // icon name
    icon: icons.astro, // Compressed website icon: https://dopiaza.org/tools/datauri/index.php
    extensions: ['.astro', '*.astro'] // .astro and <file>.astro files
  },
  readme: {
    icon: icons.readme,
    extensions: ['readme.*', 'readme']
  }
 // add more icons
});

const folder = acode.folders({
  github: { // icon name
    icon: icons.github, // Compressed website icon:  https://dopiaza.org/tools/datauri/index.php
    folder: ['.github', '.git']
  }
   // add more folder
});
```

with that way it would be much easier, would anyone be available to add?

**Comment by sebastianjnuwu** [comment]
Something like that similar to that visual studio extension

**Reply by bajrangCoder** [reply]
It isn't possible in acode to do like this

**Reply by sebastianjnuwu** [reply]
I know that, but we could implement it somehow or the own @deadlyjack, I've updated the question to try to make it more comprehensive!

**Reply by sebastianjnuwu** [reply]
Wouldn't it be possible to implement this somehow?

**Reply by bajrangCoder** [reply]
Yes , it's possible but it will require a lot efforts because we will need to change icons class from everwhere to acode.icons or the new methods

**Reply by sebastianjnuwu** [reply]
Reopening this discussion, a user managed to create a plugin that changes the folder icons according to the name. I wanted to do this. This was the beginning of the problem that I lacked knowledge of, but now I realize

**Reply by sebastianjnuwu** [reply]
Well, looking at the logic, it works, but not the way it was supposed to:

```js
import plugin from '../plugin.json';
import style from './file/style.scss';

const regex = {
  git: /\.git$/i,
};

class icons {

  async init() {
  
   this.check();
   this.style = <style textContent={style}></style>;
   document.head.append(this.style);
   
  };

  async check() {

  const list = document.querySelectorAll(".tile");

  list.forEach((e) => {

   const name = e.getAttribute("data-name");
   const type = e.getAttribute("data-type");
  
   const _type = Object.keys(regex).find((x) => regex[x].test(name));
  
   console.log(_type);
  
   if (type === "dir") (e.querySelector(".icon").classList.add(`.folder_type_${_type}`));
   
  });
  };
  
  async destroy() {
    this.style.remove();
  };
};

if (window.acode) {
   
  acode.setPluginInit(plugin.id, () => new icons().init());
 
  acode.setPluginUnmount(plugin.id, () => new icons().destroy());
  
};
```

```scss
$base: "https://localhost/__cdvfile_files-external__/plugins/sebastianjnuwu.material.icons/icons/";

$icons: (
  "git": "git.svg"
);

@each $class, $url in $icons {
 
 .list.collapsible.hidden .tile .icon.folder_type_#{$class}:before {
    display: inline-block;
    content: '';
    color: transparent;
    background-image: url(#{$base} + #{$url});
    background-size: contain;
    background-repeat: no-repeat;
    height: 1em;
    width: 1em;
}

.list.collapsible .tile .icon.folder_type_#{$class}:before {
    display: inline-block;
    content: '';
    background-image: url(#{$base} + #{$url});
    background-size: contain;
    background-repeat: no-repeat;
    height: 1em;
    width: 1em;
}

}
```
